name: liveness_capture_example
description: Demonstrates how to use the liveness_capture package.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  liveness_capture:
    path: ../

flutter:
  uses-material-design: true
