name: liveness_capture
description: A Flutter package for face liveness detection with configurable
  challenge types and auto-capture. Detect real human presence using smile,
  blink, and head turns.
version: 0.0.6
repository: https://github.com/moyinoluwalogo/flutter_liveness_capture
issue_tracker: https://github.com/moyinoluwalogo/flutter_liveness_capture/issues
topics:
  - face-detection
  - liveness
  - camera
  - biometrics
  - photo

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.0+1
  camera_android: ^0.10.10+16
  camera_avfoundation: ^0.10.1
  google_mlkit_commons: ^0.11.1
  google_mlkit_face_detection: ^0.13.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
